# configuracion cluster docker swarm con vagrant
#se cofiguran los parametros de las vms que se van a levantar
servers=[
  {
    :hostname => "manager",
    :ip => "192.168.1.1",
    :box => "williamyeh/ubuntu-trusty64-docker",
    :ram => 1024,
    :cpu => 1
  },
  {
    :hostname => "worker1",
    :ip => "192.168.1.2",
    :box => "williamyeh/ubuntu-trusty64-docker",
    :ram => 1024,
    :cpu => 1
  }
]
#inicio de configuracion vagrant 
#en el cual se crean la VM manager y VM worker1
Vagrant.configure(2) do |config|
  servers.each do |maquina|
    config.vm.define maquina[:hostname] do |node|
      node.vm.box = maquina[:box]
      node.vm.hostname = maquina[:hostname]
      node.vm.network "private_network", ip: maquina[:ip]
      if maquina[:hostname] == "manager"
        node.vm.provision "docker"
      else
        node.vm.provision "docker"
      end
      node.vm.provider "vmware_desktop" do |vb|
        vb.vmx["memsize"] =maquina[:ram]
        vb.vmx["numvcpus"]=maquina[:cpu]
        
      end
    end
  end
end
